spring:
  application:
    name: user

  # keycloak security setup
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecom

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: mohit
    password: mohit123

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90



server:
  port: 8083